[package]
name = "pycyclebio"
version = "0.0.8"
edition = "2021"
authors = ["Alex Bennett"]
description = "Oscillator functions"
license = "MIT"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
numpy = "0.18.0"

[lib]
name = "pycyclebio"
crate-type = ["cdylib"]